# Generated by Django 5.1.7 on 2025-05-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email адрес для авторизации', max_length=254, unique=True, verbose_name='Email адрес'),
        ),
    ]
