# Generated by Django 5.1.7 on 2025-05-17 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_test_testattempt_testresult_testquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('code', models.CharField(max_length=10, verbose_name='Код подтверждения')),
                ('type', models.CharField(choices=[('register', 'Регистрация'), ('reset', 'Сброс пароля')], max_length=10, verbose_name='Тип кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
            ],
            options={
                'verbose_name': 'Код подтверждения Email',
                'verbose_name_plural': 'Коды подтверждения Email',
                'indexes': [models.Index(fields=['email', 'type', 'is_used'], name='main_emailv_email_e893ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('course', models.ForeignKey(help_text='Курс, добавленный в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(help_text='Пользователь, добавивший курс в избранное', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранный курс',
                'verbose_name_plural': 'Избранные курсы',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
